apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: "tix"

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*

build:
  local:
    push: false # do not push to docker hub
  artifacts:
    - image: funkstyr/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "src/**/*.ts" # files to watch
            dest: . # where to sync file to

    - image: funkstyr/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "src/**/*.ts" # files to watch
            dest: . # where to sync file to

    - image: funkstyr/orders
      context: orders
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "src/**/*.ts" # files to watch
            dest: . # where to sync file to

    - image: funkstyr/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*" # files to watch
            dest: . # where to sync file to
